services:
  db:
    container_name: todo_pg_container
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      POSTGRES_DB: '${PG_DATABASE}'
    ports:
      - '5432:5432'
  pgadmin:
    container_name: todo_pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: alphaxsalt@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
  redis:
    container_name: todo_redis_container
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
